name: Macos arm build
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: flyci-macos-large-latest-m1

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install xmake
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      # Update xmake repository (in order to have the file that will be cached)
      - name: Update xmake repository
        run: xmake repo --update

      # Build the engine
      - name: Build Orion
        run: xmake --yes