name: Ubuntu build
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.lua'
      - '.github/workflows/build-ubuntu.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'build skip') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install mesa-common-dev


      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install mesa-common-dev

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Update xmake repository
        run: xmake repo --update

      - name: Config xmake project
        run: xmake f --mode=debug --unittest=y --yes

      - name: Build Orion
        run: xmake --yes

      - name: Run unittest
        run: xmake run unittest