name: Windows build
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.lua'
      - '.github/workflows/build-windows.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, 'build skip') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Update xmake repository
        run: xmake repo --update

      - name: Config xmake project
        run: xmake f --unittest=y --yes

      - name: Build Orion
        run: xmake --yes

      - name: Run unittest
        run: xmake run unittest